job/urls.py
from django.urls import path
from . import views

app_name = 'job'

urlpatterns = [
    path('', views.job_list, name='job_list'),
    path('add', views.add_job, name='add_job'),
    path('<str:slug>', views.job_detail, name='job_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls', namespace='jobs'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

job/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify

JOB_TYPE = (
            ('Full Time','Full Time'),
            ('Work from home','Work from home'),
            ('Part Time','Part Time'),
            ('Shift based','Shift based'),
)

def image_upload(instance, filename):
    image_name, extension = filename.split(".")
    return "jobs/%s.%s"%(instance.id,extension)

class Job(models.Model):
    owner = models.ForeignKey(User, related_name='job_owner', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    # location = 
    job_type = models.CharField(max_length=15, choices=JOB_TYPE)
    description = models.TextField(max_length=1000)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    experience = models.IntegerField(default=1)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload)

    slug = models.SlugField(blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Job,self).save(*args,**kwargs)

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

class Apply(models.Model):
    job =  models.ForeignKey(Job, related_name='apply_job', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email =models.EmailField(max_length=100)
    website = models.URLField()
    cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from .models import Job
from .form import *

def job_list(request):
    job_list = Job.objects.all().order_by('-published_at')
    paginator = Paginator(job_list, 15)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'jobs':page_obj}
    return render(request, 'job/job_list.html', context)

def job_detail(request, slug):
    job_detail = Job.objects.get(slug=slug)

    if request.method=='POST':
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.job = job_detail
            my_form.save()
            form = ApplyForm()                    # <= 1 idea
            # return redirect(f'/jobs/{slug}')    # <= 2 idea
    else:
        form = ApplyForm()

    context = {'job':job_detail, 'form1':form}
    return render(request, 'job/job_detail.html', context)

def add_job(request):
    if request.method=='POST':
        form = JobForm(request.POST, request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.owner = request.user
            my_form.save()                    
            return redirect('/jobs')            
    else:
        form = JobForm()
    return render(request, 'job/add_job.html',{'form2':form})

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block content %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Post New Job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form2 %}
                            {% buttons %}
                                <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

job/templates/job/job_list.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3>{{jobs.paginator.count}}+ Jobs Available</h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ bradcam_area  -->

<!-- job_listing_area_start  -->
<div class="job_listing_area plus_padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <div class="job_filter white-bg">
          <div class="form_inner white-bg">
            <h3>Filter</h3>
            <form action="#">
              <div class="row">
                <div class="col-lg-12">
                  <div class="single_field">
                    <input type="text" placeholder="Search keyword" />
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="single_field">
                    <select class="wide">
                      <option data-display="Location">Location</option>
                      <option value="1">Rangpur</option>
                      <option value="2">Dhaka</option>
                    </select>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="single_field">
                    <select class="wide">
                      <option data-display="Category">Category</option>
                      <option value="1">Category 1</option>
                      <option value="2">Category 2</option>
                    </select>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="single_field">
                    <select class="wide">
                      <option data-display="Experience">Experience</option>
                      <option value="1">Experience 1</option>
                      <option value="2">Experience 2</option>
                    </select>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="single_field">
                    <select class="wide">
                      <option data-display="Job type">Job type</option>
                      <option value="1">full time 1</option>
                      <option value="2">part time 2</option>
                    </select>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="single_field">
                    <select class="wide">
                      <option data-display="Qualification">
                        Qualification
                      </option>
                      <option value="1">Qualification 1</option>
                      <option value="2">Qualification 2</option>
                    </select>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="single_field">
                    <select class="wide">
                      <option data-display="Gender">Gender</option>
                      <option value="1">male</option>
                      <option value="2">female</option>
                    </select>
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="range_wrap">
            <label for="amount">Price range:</label>
            <div id="slider-range"></div>
            <p>
              <input
                type="text"
                id="amount"
                readonly
                style="
                  border: 0;
                  color: #7a838b;
                  font-size: 14px;
                  font-weight: 400;
                "
              />
            </p>
          </div>
          <div class="reset_btn">
            <button class="boxed-btn3 w-100" type="submit">Reset</button>
          </div>
        </div>
      </div>
      <div class="col-lg-9">
        <div class="recent_joblist_wrap">
          <div class="recent_joblist white-bg">
            <div class="row align-items-center">
              <div class="col-md-6">
                <h4>Job Listing</h4>
              </div>
              <div class="col-md-6">
                <div class="serch_cat d-flex justify-content-end">
                  <select>
                    <option data-display="Most Recent">Most Recent</option>
                    <option value="1">Marketer</option>
                    <option value="2">Wordpress</option>
                    <option value="4">Designer</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="job_lists m-0">
          <div class="row">
            {% for job in jobs %}
            <div class="col-lg-12 col-md-12">
              <div class="single_jobs white-bg d-flex justify-content-between">
                <div class="jobs_left d-flex align-items-center">
                  <div class="thumb">
                    <img src="{% static 'img/svg_icon/1.svg' %}" alt="" />
                  </div>
                  <div class="jobs_conetent">
                    <a href="{% url 'jobs:job_detail' job.slug %}">
                      <h4>{{job}}</h4></a>
                    <div class="links_locat d-flex align-items-center">
                      <div class="location">
                        <p><i class="fa fa-map-marker"></i> California, USA</p>
                      </div>
                      <div class="location">
                        <p><i class="fa fa-clock-o"></i>{{job.job_type}}</p>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="jobs_right">
                  <div class="apply_now">
                    <a class="heart_mark" href="#">
                      <i class="fa fa-heart"></i>
                    </a>
                    <a
                      href="{% url 'jobs:job_detail' job.slug %}"
                      class="boxed-btn3"
                      >Apply Now</a
                    >
                  </div>
                  <div class="date">
                    <p>Date line: {{job.published_at|date:"d M Y"}}</p>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
          {% if jobs.has_other_pages %}
          <div class="row">
            <div class="col-lg-12">
              <div class="pagination_wrap">
                <ul>
                  {% if jobs.has_previous %}
                  <li>
                    <a href="?page={{jobs.previous_page_number}}">
                      <i class="ti-angle-left"></i>
                    </a>
                  </li>
                  {% endif %} {% for i in jobs.paginator.page_range %}
                  <li>
                    <a href="?page={{i}}"><span>{{i}}</span></a>
                  </li>
                  {% endfor %} {% if jobs.has_next %}
                  <li>
                    <a href="?page={{jobs.next_page_number}}"
                      ><i class="ti-angle-right"></i>
                    </a>
                  </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
<!-- job_listing_area_end  -->

{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">  
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylee.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="{% static 'img/logo.png' %}" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="index.html">home</a></li>
                                            <li><a href="jobs.html">Browse Job</a></li>
                                            <li><a href="#">pages <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="candidate.html">Candidates </a></li>
                                                    <li><a href="job_details.html">job details </a></li>
                                                    <li><a href="elements.html">elements</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">blog <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="blog.html">blog</a></li>
                                                    <li><a href="single-blog.html">single-blog</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="contact.html">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">
                                    <div class="phone_num d-none d-xl-block">
                                        <a href="#">Log in</a>
                                    </div>
                                    <div class="d-none d-lg-block">
                                        <a class="boxed-btn3" href="{% url 'jobs:add_job' %}">Post a Job</a>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block content %}
    {% endblock content %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                            <p>
                                finloan@support.com <br>
                                +10 873 672 6782 <br>
                                600/D, Green road, NewYork
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/ajax-form.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'js/scrollIt.js' %}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="{% static 'js/nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- <script {% static '' %}src="js/gijgo.min.js"></script> -->
    <script src="{% static 'js/range.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.form.js' %}"></script>
    <script src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'js/mail-script.js' %}"></script>


    <script src="{% static 'js/mainn.js' %}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>